name: dart2js_playground
description: A web app that uses AngularDart Components
version: 0.0.1
author: Harry Terkelsen <het@google.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular2: '>=2.2.0 <2.3.0'
  http: ^0.11.3

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
